### ISSUE TITLE
Update RI files for Ruby 2.1.5

### ISSUE THREAD

**Issue by tknerr** [rdoc/rdoc-data#5]
RubyInstaller with Ruby 2.1.5 had been released a few weeks ago:
http://rubyinstaller.org/news/2014/11/18/rubyinstaller-1-9-3-p551-2-0-0-p598-and-2-1-5-released/

Do the RI files need an update for that?

/cc @luislavena

**Comment by zzak** [comment]
This should be fixed by upgrading to version 4.1.0.

Thanks for your patience!
